image: ruby:2.3.1

cache:
  - /usr/local/bundle

stages:
  - install
  - build
  - pages

install:
  stage: install
  script:
  - gem install bundler -v 1.16.2
  - bundle install

build:
  stage: build
  script:
  - _scripts/build.sh
  artifacts:
    paths:
    - _site

pages:
  stage: pages
  script:
  - mv ./_site ./public
  artifacts:
    paths:
    - public
  only:
  - master
