image: ruby:2.3.1

cache:
  key: gems
  paths:
    - /usr/local/bundle

stages:
  - install
  - build
  - pages

build:
  stage: install
  script:
  - gem install bundler -v 1.16.2
  - bundle install
  - _scripts/build.sh
  artifacts:
    paths:
    - _site

pages:
  stage: pages
  script:
  - mv ./_site ./public
  artifacts:
    paths:
    - public
  only:
  - master
