language: ruby
rvm:
- 2.3.1
install:
- bundle install
branches:
  only:
  - master
env:
  global:
  - JEKYLL_ENV=production
script:
- chmod +x _scripts/build.sh
- _scripts/build.sh
after_success:
- chmod +x _scripts/deploy.sh
- _scripts/deploy.sh
sudo: false
addons:
  ssh_known_hosts: overflod.chary.us
before_install:
- openssl aes-256-cbc -K $encrypted_353bc2d9e925_key -iv $encrypted_353bc2d9e925_iv
  -in travis_rsa.enc -out travis_rsa -d
- chmod 600 travis_rsa
- mv travis_rsa ~/.ssh/id_rsa