# Site settings
name: chary.us
title: chary.us
email: zbloomq@live.com
description: "No loafing."
baseurl: ""
url: "http://chary.us"
navigation:
- name: Home
  url: /
  slug: index.html
- name: Blog
  url: /blog
  slug: blog
- name: Archives
  url: /archives
  slug: archives
- name: About &amp; Contact
  url: /about
  slug: about
- name: Subscribe
  url: http://feeds.feedburner.com/charyusblog
- name: GitHub
  url: https://github.com/flotwig

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title.html
paginate: 3
paginate_path: /blog/:num
highlighter: pygments
