# Site settings
name: chary.us
title: chary.us
email: zbloomq@live.com
description: "No loafing."
baseurl: ""
url: "http://chary.us"

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title.html
paginate: 3
paginate_path: /blog/:num
highlighter: pygments