# Site settings
name: chary.us
email: zbloomq@live.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"
username: flotwig

# Build settings
markdown: kramdown
permalink: /:year/:month/:title.html
paginate: 10
highlighter: pygments