title: Zach Bloomquist
url: 'https://zach.bloomqu.ist'

plugins: [jekyll-paginate]

#Update all the sections by editing the files inside _includes folder.
# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:title.html
paginate: 3
paginate_path: /blog/:num
highlighter: rouge

defaults:
  -
    scope:
      path: "blog/"
    values:
      style: styles-3